-- ============================================================================
-- Kid device pairing — long-lived per-iPad cookie + atomic 6-digit pairing code
-- ============================================================================
-- Replaces cross-origin IAM redirects for kids' iPads. After a one-time
-- pairing flow, each device holds an HttpOnly cookie that is exchanged for a
-- short-lived Supabase session — no login screen, no PWA standalone breakage.

SET search_path TO pradotube, public;

-- ─── kid_devices ─────────────────────────────────────────────────────────────
-- One row per paired iPad. The raw secret never leaves the device cookie;
-- only the SHA-256(device_id || secret) hash lands in the database.
CREATE TABLE kid_devices (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  kid_user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  parent_user_id      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  device_secret_hash  BYTEA NOT NULL,
  device_label        TEXT,
  user_agent          TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at        TIMESTAMPTZ,
  revoked_at          TIMESTAMPTZ,
  revoked_by          UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX idx_kid_devices_kid    ON kid_devices(kid_user_id) WHERE revoked_at IS NULL;
CREATE INDEX idx_kid_devices_parent ON kid_devices(parent_user_id);

ALTER TABLE kid_devices ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON kid_devices TO authenticated;

-- The kid can see their own (non-revoked + revoked) devices; admin sees all.
-- Mutations (insert/revoke) are funneled through SECURITY DEFINER RPCs so
-- the service role never has to be available client-side.
CREATE POLICY "kid_devices_select_own" ON kid_devices
  FOR SELECT TO authenticated
  USING ((select auth.uid()) = kid_user_id);

CREATE POLICY "kid_devices_select_admin" ON kid_devices
  FOR SELECT TO authenticated
  USING (iam.is_admin('pradotube'));

-- ─── pairing_codes ───────────────────────────────────────────────────────────
-- Short-lived 6-digit codes generated by the parent admin UI and consumed
-- once on the kid's iPad. Single-use, 5-minute TTL, bound to a specific kid.
CREATE TABLE pairing_codes (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code            TEXT NOT NULL CHECK (code ~ '^[0-9]{6}$'),
  kid_user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  parent_user_id  UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at      TIMESTAMPTZ NOT NULL,
  consumed_at     TIMESTAMPTZ,
  attempts        SMALLINT NOT NULL DEFAULT 0
);

-- Partial unique index keeps only one ACTIVE row per code value at a time.
-- The expiry portion of the active-vs-stale check happens in the consume
-- RPC because now() isn't immutable and can't appear in an index predicate.
CREATE UNIQUE INDEX uniq_pairing_codes_active
  ON pairing_codes(code)
  WHERE consumed_at IS NULL;

CREATE INDEX idx_pairing_codes_kid ON pairing_codes(kid_user_id);

ALTER TABLE pairing_codes ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON pairing_codes TO authenticated;

CREATE POLICY "pairing_codes_admin" ON pairing_codes
  FOR ALL TO authenticated
  USING (iam.is_admin('pradotube'))
  WITH CHECK (iam.is_admin('pradotube'));

-- ─── consume_pairing_code RPC ────────────────────────────────────────────────
-- Atomic: validates code, marks consumed, inserts kid_devices row, returns
-- (device_id, kid_user_id). Raises on invalid/expired/missing — the caller
-- (an unauthenticated /api/devices/claim handler) translates that to a 4xx.
--
-- SECURITY DEFINER because /api/devices/claim is hit by an unauthenticated
-- iPad: there's no auth.uid() yet, RLS would deny everything. The function's
-- SQL guards (code match + not consumed + not expired) are the security
-- boundary instead.
CREATE OR REPLACE FUNCTION pradotube.consume_pairing_code(
  p_code              TEXT,
  p_device_label      TEXT,
  p_device_secret_hash BYTEA,
  p_user_agent        TEXT
)
RETURNS TABLE (
  device_id    UUID,
  kid_user_id  UUID
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pradotube, public
AS $$
DECLARE
  v_code_id        UUID;
  v_kid_user_id    UUID;
  v_parent_user_id UUID;
  v_device_id      UUID;
BEGIN
  -- Lock + consume the active code row in one statement. Concurrent claims
  -- on the same code race here; only one wins because consumed_at IS NULL is
  -- in the unique index predicate and the UPDATE flips it.
  UPDATE pairing_codes
     SET consumed_at = now()
   WHERE code = p_code
     AND consumed_at IS NULL
     AND expires_at > now()
     AND id = (
       SELECT id FROM pairing_codes
        WHERE code = p_code
          AND consumed_at IS NULL
          AND expires_at > now()
        ORDER BY created_at DESC
        LIMIT 1
        FOR UPDATE SKIP LOCKED
     )
  RETURNING id, pairing_codes.kid_user_id, pairing_codes.parent_user_id
    INTO v_code_id, v_kid_user_id, v_parent_user_id;

  IF v_code_id IS NULL THEN
    RAISE EXCEPTION 'invalid or expired pairing code'
      USING ERRCODE = 'P0002';
  END IF;

  INSERT INTO kid_devices (
    kid_user_id, parent_user_id, device_secret_hash,
    device_label, user_agent
  )
  VALUES (
    v_kid_user_id, v_parent_user_id, p_device_secret_hash,
    NULLIF(p_device_label, ''), NULLIF(p_user_agent, '')
  )
  RETURNING id INTO v_device_id;

  device_id := v_device_id;
  kid_user_id := v_kid_user_id;
  RETURN NEXT;
END;
$$;

GRANT EXECUTE ON FUNCTION pradotube.consume_pairing_code(TEXT, TEXT, BYTEA, TEXT)
  TO authenticated, anon;
REVOKE EXECUTE ON FUNCTION pradotube.consume_pairing_code(TEXT, TEXT, BYTEA, TEXT)
  FROM public;

-- ─── revoke_kid_device RPC ───────────────────────────────────────────────────
-- Admin-only. Sets revoked_at + revoked_by atomically. RLS already blocks
-- direct UPDATE for non-admins; this RPC just gives the admin a single call
-- that captures the revoker's user_id without trusting client input.
CREATE OR REPLACE FUNCTION pradotube.revoke_kid_device(p_device_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pradotube, public
AS $$
BEGIN
  IF NOT iam.is_admin('pradotube') THEN
    RAISE EXCEPTION 'admin only' USING ERRCODE = '42501';
  END IF;

  UPDATE kid_devices
     SET revoked_at = COALESCE(revoked_at, now()),
         revoked_by = (select auth.uid())
   WHERE id = p_device_id;
END;
$$;

GRANT EXECUTE ON FUNCTION pradotube.revoke_kid_device(UUID) TO authenticated;
REVOKE EXECUTE ON FUNCTION pradotube.revoke_kid_device(UUID) FROM anon, public;

-- ─── touch_kid_device RPC ────────────────────────────────────────────────────
-- Called from /api/session/refresh after a successful device verification.
-- Updates last_seen_at without exposing UPDATE privilege on the table.
CREATE OR REPLACE FUNCTION pradotube.touch_kid_device(p_device_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pradotube, public
AS $$
BEGIN
  UPDATE kid_devices
     SET last_seen_at = now()
   WHERE id = p_device_id
     AND revoked_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION pradotube.touch_kid_device(UUID) TO authenticated, anon;
REVOKE EXECUTE ON FUNCTION pradotube.touch_kid_device(UUID) FROM public;
